spring:
  application:
    name: ecommerce-api

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/springlearning}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: ${DATABASE_DRIVER_CLASS:org.postgresql.Driver}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: update   # <-- create missing tables automatically
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database-platform: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

app:
  jwt:
    secret: 2mY9QCxb4RVtIjJUyXdj2DeQNscx1YmAZ1i6pmZJ6V8=
    expiration-ms: 1800000

logging:
  level:
    org:hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
